Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'exe/**/*'

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
