AllCops:
  TargetRubyVersion: 2.6

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'exe/**/*'

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
