#!/usr/bin/env ruby

require 'redash_exporter'
require 'optparse'

params = ARGV.getopts('', 'redash-url:', 'api-key:', "dest:#{Dir.pwd}")
queries = RedashExporter::Queries.new(params['redash-url'], params['api-key'], params['dest'])
queries.export_all
